config/routes.rb
EmWebsocketChatDemo::Application.routes.draw do
  get "chat/index"

  
  devise_for :users
  root :to => "home#index"
  match 'chat'=>"home#chat"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:name
   scope :active, where("current_sign_in_at >= ? ",5.minutes.ago) #(added 5.30 hr+10 minutes ago need to check)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    @active_users = User.all
  end

  def send_chat_data
   
    render :nothing => true

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def chat
    @active_users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def clearing_span
		content_tag(:span, '', :class => 'clear')
	end
	def title(text)
		content_tag(:h1,text,:class=>'page-title')
	end
	# Returns true if sidebar disabled for current page/controller
	def sidebar_enabled?
		current_page = "#{controller.controller_name}.#{controller.action_name}"
		current_controller = controller.controller_name
		pages = %w()

		return pages.include?(current_page) || pages.include?(current_controller)
	end
	def main_content_css_class
		sidebar_enabled? ? "grid_12" : "grid_16"
	end

	# Returns the CSS class for the 'sidebar' div depending on sidebar requirement
	def sidebar_css_class
		sidebar_enabled? ? "grid_4" : "dont-show"
	end

	def active_class
		classes = {
						'home' => 'home',
						"chat.index" => 'chat',
						"registrations.edit" =>'home',
						"registrations.new" =>'register',
						"sessions.new"=>"login"
		}
		#debugger
		classes[controller.controller_name + '.' + controller.action_name] || classes[controller.controller_name] || ''
	end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/chat/index.html.erb
<% content_for :head do  %>
  <%= javascript_include_tag 'jquery.ui.chatbox' %>
  
  <!--<script src="http://localhost:8080/application.js" type="text/javascript" charset="utf-8"></script>-->
 <% end  %>
<div id="chat_div"></div>
<div id="logp"></div>
<% content_for :sidebar do %>
  <ul>
    <% @active_users.each do |user|%>
      <div id="chat_<%=  user.id %>"></div>
      <div id="chat_div_<%=  user.id %>"></div>
      <li id="<%=  user.id %>" class="connect_to_chat" user_name="<%= user.email %>" name="<%= user.name %>"><%= user.email %></li>
    <% end  %>
  </ul>
<% end %>


<script type="text/javascript">
  var logpanel = $("#logp");
 
  //    $(document).ready(function(){
  //        var counter = 0;
  //        var gap =1;
  //
  //
  //        $(".connect_to_chat").live("click",function(){
  //            // to create
  //            user_id = $(this).attr('id');
  //            user_name =  $(this).attr('user_name');
  //            chat_user_div= "chat_div_"+user_id;
  //            ews = new EmWebSocket(chat_user_div,"<%#= current_user.id %>","<%#= current_user.email%>",user_id,user_name);
  //            gap =  counter*230;
  //            counter++;
  //
  //            $("#chat_div_"+user_id).chatbox({id : "chat_"+user_id,
  //                title : user_name,
  //                user : user_name,
  //                hidden: false,
  //                offset:gap,
  //                width: 230,
  //                messageSent: function(id, user, msg){
  //                  //  this.boxManager.addMsg(user_name, msg);
  //
  //                    ews.sendmsg(ews,msg);
  //                },
  //                boxClosed: function(id) { counter--;}
  //            });
  //            // to insert a message
  //        });
  //    });
  $(document).ready(function() {
    chatboxmanager.init();

    $(".connect_to_chat").live("click",function(){

      var id         = "chat_div_"+$(this).attr("id");
      var user_id    = $(this).attr("id");
      var username   = $(this).attr("user_name");
      var firstname  = $(this).attr("name");
      var websocket  = new EmWebSocket(id,"<%= current_user.id %>","<%= current_user.email %>",user_id,username);
      chatboxmanager.addBox(id,firstname,username,websocket);
    });
  })
</script>

app/views/home/chat.html.erb
<% content_for :head do  %>
    <style type="text/css">
        #controls {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            background: #fff;
            padding: 0.5em;
            display: block;
        }

        #message {width: 80%;}

        #log {
            font-family: helvetica, arial, sans-serif;
            font-size: .8em;
            padding-bottom: 40px;
        }
    </style>
<% end  %>
<div id="log"></div>
<div id="controls">
  <hr />
  <input type="text" id="message"/>
  <input type="button" value="send" id="sendbtn" disabled="disabled">
  <input type="button" value="connect" id="connect">
  <input type="button" value="disconnect" id="disconnect" disabled="disabled">
</div>
<% content_for :sidebar do %>
    <ul>
      <% @active_users.each do |user|%>
        <li id="<%=  user.id %>" class="connect_to_chat" ><%= user.email %></li>
      <% end  %>
    </ul>
<% end %>
<script type="text/javascript">
  $(".connect_to_chat").live("click",function(){
      alert("ss");
     //$(this)
  });
    var conn;
    $(function(){
        var history = [], idx = 0;
        $("#message").focus();

        $(window).bind("focus", function(){
            $("#message").focus();
        });

        var logpanel = $("#log");

        function sendmsg(){
            if(conn && conn.readyState == 1){
                var msg = $("#message").val();
                history.unshift(msg);
                conn.send(msg);
                idx = 0;
                $("#message").val("");
            }
        };

        $("#log").bind('click', function(){
            $("#message").focus()
        });

        $("#sendbtn").bind("click", function(){
            sendmsg();
            $("#message").focus()
        });

        $("#message").bind("keydown", function(e){
            if(e.which == 13){
                sendmsg();
            }
        });

        $("#connect").bind("click", function(){
            connect()
        });

        $("#disconnect").bind("click", function(){
            conn.close()
        });

        function scrollToBottom() {
            window.scrollBy(0, document.body.scrollHeight - document.body.scrollTop);
        };

        function log(data){
            logpanel.append("<p>"+data+"</p>");
            scrollToBottom();
        };

        function connect(){
            if (window["WebSocket"]) {
                conn = new WebSocket("ws://" + "10.0.2.16" + ":8000" );

                conn.onmessage = function(evt) {
                    log(evt.data);
                };

                conn.onclose = function() {
                    log("** you have been disconnected");
                    $("#sendbtn, #disconnect").attr("disabled","disabled");
                    $("#connect").removeAttr("disabled");
                };

                conn.onopen = function(){
                    log("** you have been connected");
                    $("#sendbtn, #disconnect").removeAttr("disabled");
                    $("#connect").attr("disabled","disabled");
                    $("#message").focus()
                }
            }
        };


    });
</script>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'reset','grid','base','application','jquery-ui-1.8.6.custom','jquery.ui.chatbox'%>
  <%= javascript_include_tag :defaults %>

  <%= javascript_include_tag 'jquery-ui-1.8.6.custom.min','jquery.ui.chatbox' %>
  <script type="text/javascript" src="/javascripts/swfobject.js"></script>
  <script type="text/javascript" src="/javascripts/FABridge.js"></script>
  <script type="text/javascript" src="/javascripts/web_socket.js"></script>

  <script type="text/javascript">
    // Set URL of your WebSocketMain.swf here:
    WEB_SOCKET_SWF_LOCATION = "/javascripts/WebSocketMain.swf";
    // Set this to dump debug message from Flash to console.log:
    WEB_SOCKET_DEBUG = true;
    // Everything below is the same as using standard WebSocket.

  </script>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'em_chat.js' %>
  <title>Chat system  <%=raw ((yield(:title) || "Untitled")) %></title>
  <%= yield :head %>
  <%= csrf_meta_tag %>

</head>
<body>
<div class="container_16 every-thing">
  <div class="header">
    <div id="login_header">

      <div id="login_bar_right" class="grid_3 prefix_13">
        <ul>
          <% if !current_user.blank? %>
            <li><%=link_to "Profile  ", edit_user_registration_path,:class=>'profile',:user_id=>current_user.email %> </li>
            <li><%= link_to "Logout",  destroy_user_session_path%></li>
            <script type="text/javascript">
              function polling(id,from,from_name)
              {
                ews = new EmWebSocket(id,from,from_name,"","");
              }
            </script>
          <% else %>
            <li><%= link_to "Register ", new_user_registration_path %></li>
            <li><%= link_to "Login  ", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>


    </div>
    <div class="header-row"></div>
    <div id="main_header">
      <div class="header-content">Em Websocket Chat Demo ..... Railstech</div>
      <div id="main_nav" style="float:right;padding-right:10px;">
        <ul>
          <li class="active_class" id="home"><%= link_to "Home", root_url,:class=>active_class %></li>
          <% if current_user.blank? %>
            <li class="active_class" id="login"><%= link_to "Login", new_user_session_path,:class=>active_class %></li>
            <li class="active_class" id="register"><%= link_to "Register ", new_user_registration_path,:class=>active_class %></li>
          <% else %>
            <script>polling("polling","<%= current_user.id %>","<%= current_user.email %>");</script>
            <li class="active_class" id="chat"><%= link_to "chat", chat_index_path ,:class=>active_class%></li>
          <% end %>

        </ul>
      </div>


    </div>
    <div id="sub_nav">

    </div>

  </div>
  <%= clearing_span %>
  <div id="content" >
    <div id="main_content" class="grid_12">
      <div id="polling">&nbsp;</div>
      <%= yield %>

    </div>
    <div id="sidebar" class="grid_4">
      <%=yield :sidebar %>

    </div>
    <%= clearing_span %>
  </div>

  <div class="push"></div>

</div>
<%= clearing_span %>
<div  class="container_16" id="footer-wrapper">
  <div class="footer-row"></div>
  <div id="footer">

    <p class="copyright">&copy; 2010 <a href="http://raistech.com">Amar Daxini</a> & <a href='http://virenegi.blogspot.com'> Viren Negi</a></p>
  </div>

  <%= yield :javascript %>
  <script>
    function addActive()
    {
      $(".active_class").removeClass('active');
      var active_id = $(".active_class:first a").attr('class');
      
      $(".active_class").each(function(){
        if($(this).attr('id')==active_id)
        {
          $(this).addClass('active');
          return;
        }


      });
    }
    $(document).ready(function(){

      addActive();
    });
  </script>
</div>
</body>
</html>